# Generated by Django 3.2.19 on 2023-05-13 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factory_app', '0002_rename_pprocedure_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
