# Generated by Django 3.2.19 on 2023-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_app', '0003_batch_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
