# Generated by Django 3.2.19 on 2023-05-13 21:29

import django.core.files.storage
from django.db import migrations, models
import neoxam.harry.models


class Migration(migrations.Migration):

    dependencies = [
        ('harry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonuntranslated',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Mustapha\\Desktop\\iadev5.0-master\\iadev5.0-master\\data\\var\\harry'), upload_to=neoxam.harry.models.json_upload_to),
        ),
        migrations.AlterField(
            model_name='push',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Mustapha\\Desktop\\iadev5.0-master\\iadev5.0-master\\data\\var\\harry'), upload_to=neoxam.harry.models.untranslated_upload_to),
        ),
    ]
