# Generated by Django 3.2.19 on 2023-05-13 21:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champagne', '0002_alter_compilation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='src',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Mustapha\\Desktop\\iadev5.0-master\\iadev5.0-master\\data\\var\\champagne'), upload_to='%Y/%m', verbose_name='Source'),
        ),
    ]
